import { Inter } from 'next/font/google'
import './globals.css'
import PrivateRoute from '@/component/Protected Route/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Golfhom | Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivateRoute>
          {children}
        </PrivateRoute>
      </body>
    </html>
  )
}