import Sidebar from "@/component/Sidebar/page"
import Header from "@/component/Header/page";
import '@/app/globals.css'
export const metadata = {
    title: 'Golfhom | Admin',
    description: 'Generated by Golfhom',
}

export default function RootLayout({ children }) {
    return (
        <>
            <div className="flex flex-col">
                <Header />
                <div className="flex flex-row">
                    <div className="lg:basis-[22%] z-50 ">
                        <Sidebar />
                    </div>

                    <div className='bg-gray-200 w-full lg:basis-5/6 z-50'>
                        <div className="my-5 px-8 py-4 flex flex-col gap-8 min-h-screen">
                            {children}
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}